### PR TITLE
Update CMakeLists.txt (For TEST)

### PR DESCRIPTION
**Pull request by qiaojbao**

### CODE REVIEW

**Review by jinjianrong — APPROVED** [review]

**Comment by qiaojbao** [comment]
retest this please

**Comment by qiaojbao** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit ad0e7e169d7455afb07ab9fffdcdc2b11ee9000b
<details><summary>CTS tests (Failed: 1/39917)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi21</summary><ul>

<li>Passed: 17444/39917 (43.7%)</li>
<li><details><summary>Failed: 1/39917 (0.0%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.amd_ray_query.stress.graphics.frag.triangles
Stack trace: Fail
```
</p></details></li>

<li>Not Supported: 22472/39917 (56.3%)</li><li>Warnings: 0/39917 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit ad0e7e169d7455afb07ab9fffdcdc2b11ee9000b
<details><summary>CTS tests (Failed: 68/32983)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi21</summary><ul>

<li>Passed: 16815/32983 (51.0%)</li>
<li><details><summary>Failed: 68/32983 (0.2%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.ray_query.acceleration_structures.empty.ahit_shader.gpu_built.index_uint16.no_primitives_bottom
Stack trace: Flake

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.different_instances.padded.0_0_compaction_lowmemory_bottomgeneric
Stack trace: Flake

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.identical_instances.nopadding.0_update_compaction_lowmemory_bothgeneric
Stack trace: Flake

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.identical_instances.padded.0_update_0_lowmemory_bottomgeneric
Stack trace: Flake

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs.identical_instances.padded.fasttrace_0_0_0
Stack trace: Flake

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs_aop.different_instances.padded.fastbuild_update_compaction_0_bothgeneric
Stack trace: Flake

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs_aop.different_instances_aop.nopadding.0_0_0_lowmemory_topgeneric
Stack trace: Flake

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.aabbs_aop.identical_instances_aop.nopadding.fasttrace_update_0_0
Stack trace: Flake

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.triangles.different_instances.nopadding.0_update_compaction_lowmemory_topgeneric
Stack trace: Flake

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.triangles.identical_instances.nopadding.fasttrace_0_0_0_topgeneric
Stack trace: Flake

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.triangles.identical_instances.nopadding.fasttrace_update_0_0_bottomgeneric
Stack trace: Flake

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.triangles.identical_instances.nopadding.fasttrace_update_compaction_0_bottomgeneric
Stack trace: Flake

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.triangles_aop.different_instances.padded.fastbuild_0_compaction_lowmemory_bothgeneric
Stack trace: Flake

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.triangles_aop.different_instances.padded.fasttrace_update_compaction_lowmemory_bottomgeneric
Stack trace: Flake

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.triangles_aop.different_instances_aop.padded.0_0_compaction_0_bothgeneric
Stack trace: Flake

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.chit_shader.gpu_built.triangles_aop.identical_instances_aop.nopadding.0_0_compaction_lowmemory_bottomgeneric
Stack trace: Flake

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.compute_shader.gpu_built.aabbs.different_instances_aop.nopadding.0_0_compaction_lowmemory_bottomgeneric
Stack trace: Flake

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.compute_shader.gpu_built.aabbs.different_instances_aop.padded.0_0_compaction_lowmemory_topgeneric
Stack trace: Flake

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.compute_shader.gpu_built.aabbs.identical_instances.nopadding.fastbuild_update_0_0_bottomgeneric
Stack trace: Flake

FAILURE: dEQP-VK.ray_query.acceleration_structures.flags.compute_shader.gpu_built.aabbs.identical_instances.nopadding.fasttrace_0_0_0_bothgeneric
Stack trace: Flake
...
```
</p></details></li>

<li>Not Supported: 16100/32983 (48.8%)</li><li>Warnings: 0/32983 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by amdvlk-admin** [comment]
### Test summary for commit ad0e7e169d7455afb07ab9fffdcdc2b11ee9000b
<details><summary>CTS tests (Failed: 0/32983)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi21</summary><ul>

<li>Passed: 16883/32983 (51.2%)</li>
<li>Failed: 0/32983 (0.0%)</li>
<li>Not Supported: 16100/32983 (48.8%)</li><li>Warnings: 0/32983 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request closed without merging**
