### PR TITLE
Update LICENSE

### PR DESCRIPTION
**Pull request by qiaojbao**

### CODE REVIEW

**Comment by amdvlk-admin** [comment]
### Test summary for commit b5812091a74bbe6cb6f208846777e98293e830a9
<details><summary>CTS tests (Failed: 0/73498)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi21</summary><ul>

<li>Passed: 38491/73498 (52.4%)</li>
<li>Failed: 0/73498 (0.0%)</li>
<li>Not Supported: 35007/73498 (47.6%)</li><li>Warnings: 0/73498 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by qiaojbao** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit b5812091a74bbe6cb6f208846777e98293e830a9
<details><summary>CTS tests (Failed: 0/376)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi21</summary><ul>

<li>Passed: 305/376 (81.1%)</li>
<li>Failed: 0/376 (0.0%)</li>
<li>Not Supported: 71/376 (18.9%)</li><li>Warnings: 0/376 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by qiaojbao** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit b5812091a74bbe6cb6f208846777e98293e830a9
<details><summary>CTS tests (Failed: 0/376)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi21</summary><ul>

<li>Passed: 305/376 (81.1%)</li>
<li>Failed: 0/376 (0.0%)</li>
<li>Not Supported: 71/376 (18.9%)</li><li>Warnings: 0/376 (0.0%)</li>
</ul></details>


</ul></details>

**Comment by qiaojbao** [comment]
retest this please

**Comment by qiaojbao** [comment]
retest this please

**Comment by amdvlk-admin** [comment]
### Test summary for commit b5812091a74bbe6cb6f208846777e98293e830a9
<details><summary>CTS tests (Failed: 160/39917)</summary><ul><li>Built with version 1.3.0.0</li>
<details open><summary>Ubuntu 22.04, Navi21</summary><ul>

<li>Passed: 10/39917 (0.0%)</li>
<li><details><summary>Failed: 160/39917 (0.4%)</summary><p>


Failures:
```
FAILURE: dEQP-VK.amd_ray_query.builtin.graphics.frag.barycentrics
Stack trace: Crash

FAILURE: dEQP-VK.amd_ray_query.builtin.graphics.frag.customIndex_geometryIndex
Stack trace: Crash

FAILURE: dEQP-VK.amd_ray_query.builtin.graphics.frag.frontFace
Stack trace: Crash

FAILURE: dEQP-VK.amd_ray_query.builtin.graphics.frag.geometryIndex
Stack trace: Crash

FAILURE: dEQP-VK.amd_ray_query.builtin.graphics.frag.instanceId
Stack trace: Crash

FAILURE: dEQP-VK.amd_ray_query.builtin.graphics.frag.instanceShaderBindingTableOffset
Stack trace: Crash

FAILURE: dEQP-VK.amd_ray_query.builtin.graphics.frag.non_opaque_aabbopaque
Stack trace: Crash

FAILURE: dEQP-VK.amd_ray_query.builtin.graphics.frag.non_opaque_int_ray_dir
Stack trace: Crash

FAILURE: dEQP-VK.amd_ray_query.builtin.graphics.frag.non_opaque_int_ray_object_to_world
Stack trace: Crash

FAILURE: dEQP-VK.amd_ray_query.builtin.graphics.frag.non_opaque_int_ray_orgn
Stack trace: Crash

FAILURE: dEQP-VK.amd_ray_query.builtin.graphics.frag.non_opaque_int_ray_world_to_object
Stack trace: Crash

FAILURE: dEQP-VK.amd_ray_query.builtin.graphics.frag.opaque_aabbopaque
Stack trace: Crash

FAILURE: dEQP-VK.amd_ray_query.builtin.graphics.frag.opaque_int_ray_dir
Stack trace: Crash

FAILURE: dEQP-VK.amd_ray_query.builtin.graphics.frag.opaque_int_ray_object_to_world
Stack trace: Crash

FAILURE: dEQP-VK.amd_ray_query.builtin.graphics.frag.opaque_int_ray_orgn
Stack trace: Crash

FAILURE: dEQP-VK.amd_ray_query.builtin.graphics.frag.opaque_int_ray_world_to_object
Stack trace: Crash

FAILURE: dEQP-VK.amd_ray_query.builtin.graphics.frag.primitiveId
Stack trace: Crash

FAILURE: dEQP-VK.amd_ray_query.builtin.graphics.frag.ray_direction
Stack trace: Crash

FAILURE: dEQP-VK.amd_ray_query.builtin.graphics.frag.ray_origin
Stack trace: Crash

FAILURE: dEQP-VK.amd_ray_query.builtin.graphics.frag.ray_tmin_rayFlags
Stack trace: Crash
...
```
</p></details></li>

<li>Not Supported: 39747/39917 (99.6%)</li><li>Warnings: 0/39917 (0.0%)</li>
</ul></details>


</ul></details>

**Pull request closed without merging**
